docs: improvements to REST API tutorial
Quansight/ragna pull request #198
Opened 2023-11-11 19:16 UTC by agilgur5

## Summary

Several documentation improvements to the REST API tutorial

Basically the equivalent of #196 but for the REST API tutorial instead

## Details

- additions:
  - add link to REST API reference and Python API reference

- stylistic improvements:
  - simplifications:
    - "For demonstration or exploration alone" -> "For demonstration purposes"
    - "make sure the username and password provided are identical" -> "make the username and password identical"
    - "as per your configuration" -> "based on your configuration"
    - "As per the demo configuration" -> "For the demo"
    - see also [k8s style guide on simple and direct language](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language) (which I use and reference often for docs -- it's a pretty great style guide!)
  - consistency:
    - "Large Language Model" -> "LLM"
      - almost everywhere else in the docs, including further up in this same doc, "LLM" is used as short-hand
        - "Large Language Model" can be explained in the first, intro doc, and then short-hand used everywhere after
    - "you can start" -> "you can now start"
      - "you can now" is used in other parts of this doc and is indicative of a sequence of steps
  - code style:
    - remove new line after `!!! tip`
      - otherwise most markdown editors will recognize the block as a code block due to the 4 space indentation

- fix various spelling and grammar errors and typos:
  - "workflows starts" -> "workflows start"
  - "can select the components" -> "can select components"
    - the components are already described immediately after
  - "you terminal" -> "your terminal"
  - "a HTTP client" -> "an HTTP client"
  - "authentication into your user session" -> "authenticating your user session"
    - remove extra commas here as well
  - "you set" -> "set"
  - "And, use" -> "And use"
  - "(LLM)s" -> "(LLMs)"

2023-11-11 20:44 UTC, pmeier requested changes
See https://github.com/Quansight/ragna/pull/197#pullrequestreview-1726123408 for my inline comment. I'll let @pavithraes handle the rest.

2023-11-11 20:44 UTC, pmeier commented on docs/tutorials/rest-api.md
> +    Alternatively, you can make the username and password identical.
```suggestion

    Alternatively, you can make the username and password identical.
```

2023-11-12 19:43 UTC, agilgur5 commented on docs/tutorials/rest-api.md
> +    Alternatively, you can make the username and password identical.
added back the new line

2023-11-13 13:09 UTC, pavithraes reviewed
Thanks, @agilgur5! Looks great, and again all suggestions are related to [formatting (line length)](https://github.com/Quansight/ragna/actions/runs/6842737194/job/18619224407?pr=198#step:6:31), we can merge after! 🌻

2023-11-13 23:06 UTC, pmeier approved these changes
Thanks @agilgur5 for the PR and @pavithraes for the review!

2023-11-13 23:06 UTC, merged