added page(s) to 341 line
Quansight/ragna pull request #274
Opened 2024-01-16 13:56 UTC by MuhammadHasnain77

2024-01-16 13:58 UTC, MuhammadHasnain77 commented
is it correct?
I am new to github so I don't know much about it.

2024-01-16 14:39 UTC, pmeier requested changes
Hey @MuhammadHasnain77 and welcome to the Ragna project :wave: Unfortunately, it is not in the right place or better not in the right place I wanted it to have. Let me add a screenshot to the issue to get a better sense.

2024-01-17 07:46 UTC, pmeier commented on ragna/deploy/_ui/central_view.py
> +            pages = source["document"].get("pages")
`source["document"]` does not have a field called `pages`. You can find the schemas here

https://github.com/Quansight/ragna/blob/38f75f6d88e74f72c030ef50045315b81eb203aa/ragna/deploy/_api/schemas.py#L35-L39

https://github.com/Quansight/ragna/blob/38f75f6d88e74f72c030ef50045315b81eb203aa/ragna/deploy/_api/schemas.py#L18-L20

The `location` field is what you want. You can check if it is a non-empty string and if yes, prepend `page(s)` to it. You can use the following existing block for it:

https://github.com/Quansight/ragna/blob/38f75f6d88e74f72c030ef50045315b81eb203aa/ragna/deploy/_ui/central_view.py#L339-L340

2024-01-18 14:26 UTC, pmeier commented
@MuhammadHasnain77 we ended up touching the relevant lines in #264 and fixed #272 in the process. Thus, I'm closing this PR. Still, thanks for the effort.

2024-01-18 14:26 UTC, closed without merging